config/routes.rb
Rails.application.routes.draw do

  mount Spree::Core::Engine, :at => '/'
  Spree::Core::Engine.routes.draw do
    namespace :admin do
      resources :taxonomies, :as => :categories, path: :categories do
        collection do
          post :update_positions
        end
        resources :taxons, :as => :catalogs, path: :catalogs
      end

      resources :taxons, :as => :catalogs, path: :catalogs, only: [:index, :show] do
        collection do
          get :search
        end
      end

      resources :properties do
        collection do
          get :filtered
          post :update_positions
        end
        resources :sub_properties
      end

      resources :sub_properties, only: [:index, :show] do
        collection do
          get :search
        end
      end
    end

    namespace :api do
      resources :taxonomies, :as => :categories, path: :categories do
        member do
          get :jstree
        end
        resources :taxons, :as => :catalogs, path: :catalogs do
          member do
            get :jstree
          end
        end
      end

      resources :properties do
        member do
          get :jstree
        end
        resources :sub_properties do
          member do
            get :jstree
          end
        end
      end
    end
  end

end

app/controllers/spree/admin/taxonomies_controller.rb
module Spree
  module Admin
    class TaxonomiesController < ResourceController
      private

      def location_after_save
        if @taxonomy.created_at == @taxonomy.updated_at
          edit_admin_category_url(@taxonomy)
        else
          admin_categories_url
        end
      end
    end
  end
end

app/controllers/spree/api/taxonomies_controller.rb
module Spree
  module Api
    class TaxonomiesController < Spree::Api::BaseController
      def index
        @taxonomies = paginate(taxonomies)
        respond_with(@taxonomies)
      end

      def new
      end

      def show
        respond_with(taxonomy)
      end

      # Because JSTree wants parameters in a *slightly* different format
      def jstree
        show
      end

      def create
        authorize! :create, Taxonomy
        @taxonomy = Taxonomy.new(taxonomy_params)
        if @taxonomy.save
          respond_with(@taxonomy, status: 201, default_template: :show)
        else
          invalid_resource!(@taxonomy)
        end
      end

      def update
        authorize! :update, taxonomy
        if taxonomy.update_attributes(taxonomy_params)
          respond_with(taxonomy, status: 200, default_template: :show)
        else
          invalid_resource!(taxonomy)
        end
      end

      def destroy
        authorize! :destroy, taxonomy
        taxonomy.destroy
        respond_with(taxonomy, status: 204)
      end

      private

      def taxonomies
        @taxonomies = Taxonomy.
          accessible_by(current_ability, :read).
          order('name').
          includes(root: :children).
          ransack(params[:q]).
          result
      end

      def taxonomy
        @taxonomy ||= Taxonomy.accessible_by(current_ability, :read).find(params[:id])
      end

      def taxonomy_params
        if params[:taxonomy] && !params[:taxonomy].empty?
          params.require(:taxonomy).permit(permitted_taxonomy_attributes)
        else
          {}
        end
      end
    end
  end
end

app/views/spree/admin/taxonomies/_form.html.erb
<div data-hook="admin_inside_taxonomy_form" class="field align-center">
  <%= f.field_container :name do %>
    <%= f.label :name, class: 'required' %><br />
    <%= error_message_on :taxonomy, :name, :class => 'fullwidth title' %>
    <%= text_field :taxonomy, :name %>
  <% end %>
</div>

app/views/spree/admin/taxonomies/_list.html.erb
<table class="index sortable" id='listing_taxonomies' data-hook data-sortable-link="<%= update_positions_admin_taxonomies_url %>">
  <colgroup>
    <col style="width: 10%">
    <col style="width: 75%">
    <col style="width: 15%">
  </colgroup>
  <thead>
    <tr data-hook="taxonomies_header">
      <th class="no-border"></th>
      <th><%= Spree::Category.human_attribute_name(:name) %></th>
      <th class="actions"></th>
    </tr>
  </thead>
  <tbody>
    <% @taxonomies = Spree::Category.all %>
    <% @taxonomies.each do |taxonomy| %>
      <tr id="<%= spree_dom_id taxonomy %>" data-hook="taxonomies_row" class="<%= cycle('odd', 'even')%>">
        <td class="no-border">
          <% if can?(:update_positions, Spree::Category) %>
            <span class="handle"></span>
          <% end %>
        </td>
        <td class="align-center"><%= taxonomy.name %></td>
        <td class="actions">
          <% if can?(:update, taxonomy) %>
            <%= link_to_edit taxonomy, :no_text => true %>
          <% end %>
          <% if can?(:destroy, taxonomy) %>
            <%= link_to_delete taxonomy, :no_text => true %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/taxonomies/edit.erb
<% admin_breadcrumb(link_to plural_resource_name(Spree::Product), spree.admin_products_path) %>
<% admin_breadcrumb(link_to plural_resource_name(Spree::Category), spree.admin_categories_path) %>
<% admin_breadcrumb(Spree.t(:edit_category)) %>


<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:back_to_category_list), spree.admin_categories_path, :id => 'admin_categories_link', :class => 'fa fa-arrow-left' %>
  </li>
  <li>
    <%= button_link_to Spree.t(:add_catalog), spree.admin_categories_path, { class: 'add-taxon-button fa fa-plus' } %>
  </li>
<% end %>

<%= form_for [:admin, @taxonomy] do |f| %>
  <fieldset class="no-border-top">
    <%= render :partial => 'form', :locals => { :f => f } %>
    <div class="filter-actions actions">
      <%= button Spree.t('actions.update') %>
      <%= button_link_to Spree.t('actions.cancel'), admin_categories_path %>
    </div>
  </fieldset>


  <div>
    <script>
      Spree.routes.taxonomy_path = "<%= spree.api_category_path(@taxonomy) %>";
      Spree.routes.taxonomy_taxons_path = "<%= spree.api_category_catalogs_path(@taxonomy) %>";
      Spree.routes.admin_taxonomy_taxons_path = "<%= spree.admin_category_catalogs_path(@taxonomy) %>";
    </script>
    <div id="taxonomy_tree" class="tree" data-taxonomy-id="<%= @taxonomy.id %>"></div>
  </div>
<% end %>

app/views/spree/admin/taxonomies/index.html.erb
<% admin_breadcrumb(link_to plural_resource_name(Spree::Product), spree.admin_products_path) %>
<% admin_breadcrumb(plural_resource_name(Spree::Category).pluralize) %>

<% content_for :page_actions do %>
    <% if can?(:create, Spree::Category) %>
        <li>
          <%= button_link_to Spree.t(:new_category), spree.new_admin_category_url, :id => 'admin_new_category_link', :class => 'fa fa-plus' %>
        </li>
    <% end %>
<% end %>

<% if @taxonomies.any? %>
    <div id="list-taxonomies" data-hook>
      <%= render 'list' %>
    </div>
<% else %>
    <div class="alpha twelve columns no-objects-found">
      <%= render 'spree/admin/shared/no_objects_found',
                 resource: Spree::Category,
                 new_resource_url: new_object_url %>
    </div>
<% end %>

app/views/spree/admin/taxonomies/new.html.erb
<% admin_breadcrumb(link_to (Spree::Product), spree.admin_products_path) %>
<% admin_breadcrumb(link_to (Spree::Category).to_s.pluralize, spree.admin_taxonomies_path) %>
<% admin_breadcrumb(Spree.t(:new_category)) %>


<% content_for :page_actions do %>
    <li>
      <%= button_link_to Spree.t(:back_to_category_list), spree.admin_categories_path, :id => 'admin_categories_link', :class => 'fa fa-arrow-left' %>
    </li>
<% end %>

<%= form_for [:admin, @taxonomy] do |f| %>

  <%= render :partial => 'form', :locals => { :f => f } %>
  <fieldset class="no-border-top">
    <br>
    <div class="filter-actions actions" data-hook="buttons">
      <%= button Spree.t('actions.create') %>
    </div>
  </fieldset>
<% end %>