config/routes.rb
Rails.application.routes.draw do

  mount Spree::Core::Engine, :at => '/'
  Spree::Core::Engine.routes.draw do
    namespace :admin do
      resources :taxonomies, :as => :categories, path: :categories do
        collection do
          post :update_positions
        end
        resources :taxons, :as => :catalogs, path: :catalogs
      end

      resources :taxons, :as => :catalogs, path: :catalogs, only: [:index, :show] do
        collection do
          get :search
        end
      end

      resources :properties do
        collection do
          get :filtered
          post :update_positions
        end
        resources :sub_properties
      end

      resources :sub_properties, only: [:index, :show] do
        collection do
          get :search
        end
      end
    end

    namespace :api do
      resources :taxonomies, :as => :categories, path: :categories do
        member do
          get :jstree
        end
        resources :taxons, :as => :catalogs, path: :catalogs do
          member do
            get :jstree
          end
        end
      end

      resources :properties do
        member do
          get :jstree
        end
        resources :sub_properties do
          member do
            get :jstree
          end
        end
      end
    end
  end

end

app/controllers/spree/admin/taxons_controller.rb
module Spree
  module Admin
    class TaxonsController < Spree::Admin::BaseController
      respond_to :html, :json, :js

      def index
      end

      def search
        if params[:ids]
          @taxons = Spree::Taxon.where(id: params[:ids].split(','))
        else
          @taxons = Spree::Taxon.limit(20).ransack(name_cont: params[:q]).result
        end
      end

      def create
        @taxonomy = Taxonomy.find(params[:taxonomy_id])
        @taxon = @taxonomy.taxons.build(params[:taxon])
        if @taxon.save
          respond_with(@taxon) do |format|
            format.json { render json: @taxon.to_json }
          end
        else
          flash[:error] = Spree.t('errors.messages.could_not_create_taxon')
          respond_with(@taxon) do |format|
            format.html { redirect_to @taxonomy ? edit_admin_category_url(@taxonomy) : admin_categories_url }
          end
        end
      end

      def edit
        @taxonomy = Taxonomy.find(params[:category_id])
        @taxon = @taxonomy.taxons.find(params[:id])
        @permalink_part = @taxon.permalink.split("/").last
      end

      def update
        @taxonomy = Taxonomy.find(params[:taxonomy_id])
        @taxon = @taxonomy.taxons.find(params[:id])
        parent_id = params[:taxon][:parent_id]
        new_position = params[:taxon][:position]

        if parent_id
          @taxon.parent = Taxon.find(parent_id.to_i)
        end

        if new_position
          @taxon.child_index = new_position.to_i
        end

        if params[:permalink_part]
          @taxon.permalink_part = params[:permalink_part].to_s
        end

        @taxon.assign_attributes(taxon_params)

        if @taxon.save
          flash[:success] = flash_message_for(@taxon, :successfully_updated)
        end

        respond_with(@taxon) do |format|
          format.html { redirect_to edit_admin_category_url(@taxonomy) }
        end
      end

      def destroy
        @taxon = Taxon.find(params[:id])
        @taxon.destroy
        respond_with(@taxon) { |format| format.json { render json: '' } }
      end

      private

      def taxon_params
        params.require(:taxon).permit(permitted_taxon_attributes)
      end
    end
  end
end

app/controllers/spree/api/taxons_controller.rb
module Spree
  module Api
    class TaxonsController < Spree::Api::BaseController
      def index
        if taxonomy
          @taxons = taxonomy.root.children
        elsif params[:ids]
          @taxons = Spree::Taxon.accessible_by(current_ability, :read).where(id: params[:ids].split(','))
        else
          @taxons = Spree::Taxon.accessible_by(current_ability, :read).order(:taxonomy_id, :lft).ransack(params[:q]).result
        end

        @taxons = paginate(@taxons)
        respond_with(@taxons)
      end

      def new
      end

      def show
        @taxon = taxon
        respond_with(@taxon)
      end

      def jstree
        show
      end

      def create
        authorize! :create, Taxon
        @taxon = Spree::Taxon.new(taxon_params)
        @taxon.taxonomy_id = params[:category_id]
        taxonomy = Spree::Taxonomy.find_by(id: params[:category_id])

        if taxonomy.nil?
          @taxon.errors.add(:taxonomy_id, I18n.t('spree.api.invalid_taxonomy_id'))
          invalid_resource!(@taxon) && return
        end

        @taxon.parent_id = taxonomy.root.id unless params[:taxon][:parent_id]

        if @taxon.save
          respond_with(@taxon, status: 201, default_template: :show)
        else
          invalid_resource!(@taxon)
        end
      end

      def update
        authorize! :update, taxon
        if taxon.update_attributes(taxon_params)
          respond_with(taxon, status: 200, default_template: :show)
        else
          invalid_resource!(taxon)
        end
      end

      def destroy
        authorize! :destroy, taxon
        taxon.destroy
        respond_with(taxon, status: 204)
      end

      def products
        # Returns the products sorted by their position with the classification
        # Products#index does not do the sorting.
        taxon = Spree::Taxon.find(params[:id])
        @products = paginate(taxon.products.ransack(params[:q]).result)
        render "spree/api/products/index"
      end

      private

      def default_per_page
        500
      end

      def taxonomy
        if params[:category_id].present?
          @taxonomy ||= Spree::Taxonomy.accessible_by(current_ability, :read).find(params[:category_id])
        end
      end

      def taxon
        @taxon ||= taxonomy.taxons.accessible_by(current_ability, :read).find(params[:id])
      end

      def taxon_params
        if params[:taxon] && !params[:taxon].empty?
          params.require(:taxon).permit(permitted_taxon_attributes)
        else
          {}
        end
      end
    end
  end
end

app/views/spree/admin/taxons/edit.html.erb
<% admin_breadcrumb(Spree.t(:catelog_edit)) %>


<% content_for :page_actions do %>
    <li>
      <%= button_link_to Spree.t(:back_to_categories_list), spree.admin_categories_path, :class=>'fa fa-arrow-left' %>
    </li>
<% end %>

<%# Because otherwise the form would attempt to use to_param of @taxon %>
<% form_url = admin_taxonomy_taxon_path(@taxonomy.id, @taxon.id) %>
<%= form_for [:admin, @taxonomy, @taxon], :method => :put, :url => form_url, :html => { :multipart => true } do |f| %>
    <%= render 'form', :f => f %>

    <div class="form-buttons filter-actions" data-hook="buttons">
      <%= button Spree.t('actions.update') %>
      <%= button_link_to Spree.t('actions.cancel'), edit_admin_category_url(@taxonomy) %>
    </div>
<% end %>

<% content_for :head do %>
    <%= javascript_tag do -%>
        $(document).ready(function() {
        var field  = $('#permalink_part'),
        target = $('#permalink_part_display'),
        permalink_part_default = target.text().trim();

        target.text(permalink_part_default + field.val());
        field.on('keyup blur', function () {
        target.text(permalink_part_default + $(this).val());
        });
        });
    <% end -%>
<% end %>

app/views/spree/admin/taxons/index.html.erb
<% admin_breadcrumb(link_to Spree::Product.model_name.human(count: :other), spree.admin_products_path) %>
<% admin_breadcrumb(Spree.t('catalogs')) %>

<% content_for :table_filter_title do %>
  <%= Spree.t(:choose_a_catalog_to_sort_products_for) %>
<% end %>

<% content_for :table_filter do %>
  <div data-hook="admin_orders_index_search" class="columns six">
    <input type='text' id='taxon_id' />
  </div>
<% end %>

<div class='sixteen columns'>
  <div id='taxon_products' class='list-group'></div>
</div>